# Generated by Django 4.2.7 on 2025-05-31 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('titles', 'Títulos'), ('description', 'Descrição'), ('chapters', 'Capítulos'), ('complete', 'Pacote Completo')], max_length=20)),
                ('use_markdown', models.BooleanField(default=False)),
                ('title_types', models.JSONField(blank=True, default=list)),
                ('description_type', models.CharField(blank=True, max_length=50, null=True)),
                ('max_chapters', models.IntegerField(blank=True, default=6, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('language_detected', models.CharField(blank=True, max_length=10, null=True)),
                ('generated_content', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Geração de Conteúdo',
                'verbose_name_plural': 'Gerações de Conteúdo',
                'db_table': 'content_generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_type', models.CharField(max_length=50)),
                ('title_text', models.CharField(max_length=500)),
                ('justification', models.TextField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('content_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='content_generation.contentgeneration')),
            ],
            options={
                'verbose_name': 'Título Gerado',
                'verbose_name_plural': 'Títulos Gerados',
                'db_table': 'generated_titles',
            },
        ),
        migrations.CreateModel(
            name='GeneratedChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField()),
                ('timestamp', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('content_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='content_generation.contentgeneration')),
            ],
            options={
                'verbose_name': 'Capítulo Gerado',
                'verbose_name_plural': 'Capítulos Gerados',
                'db_table': 'generated_chapters',
                'ordering': ['content_generation', 'chapter_number'],
            },
        ),
    ]
