# Generated by Django 4.2.7 on 2025-05-31 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcriptions', '0001_initial'),
        ('content_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgeneration',
            name='transcription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_generations', to='transcriptions.transcription'),
        ),
    ]
