# Generated by Django 4.2.7 on 2025-05-31 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_generation', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentgeneration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_generations', to=settings.AUTH_USER_MODEL),
        ),
    ]
