# Generated by Django 4.2.7 on 2025-05-31 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube'), ('audio_upload', 'Upload de Áudio'), ('video_upload', 'Upload de Vídeo')], max_length=20)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='transcriptions/audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='transcriptions/video/')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('language_detected', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('transcription_text', models.TextField(blank=True, null=True)),
                ('include_timestamps', models.BooleanField(default=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('file_size_mb', models.FloatField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Transcrição',
                'verbose_name_plural': 'Transcrições',
                'db_table': 'transcriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptionSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_number', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.TextField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='transcriptions.transcription')),
            ],
            options={
                'verbose_name': 'Segmento de Transcrição',
                'verbose_name_plural': 'Segmentos de Transcrição',
                'db_table': 'transcription_segments',
                'ordering': ['transcription', 'segment_number'],
            },
        ),
    ]
